Project init, Radar model, superuser created.
deployed/tech-radar-admin pull request #1
Opened 2024-12-20 11:56 UTC by justgruba

2024-12-20 13:43 UTC, lchojnacki reviewed
Brakuje mi tutaj:

2024-12-20 13:43 UTC, lchojnacki commented on techradar/__pycache__/__init__.cpython-313.pyc
Usuń proszę wszystkie pliki .pyc :smile: 

```
find . -name '*.pyc' -type f -delete
```

A potem dodaj `.gitignore`, który zapobiegnie ich ponownemu dodaniu:

https://www.toptal.com/developers/gitignore/api/python,django

2024-12-20 13:43 UTC, lchojnacki commented on techradar/radars/admin.py
> +admin.site.register(Radar)
Spróbuj dodać klasę admina `RadarAdmin` z `list_display`: https://docs.djangoproject.com/en/5.1/ref/contrib/admin/

2024-12-20 13:43 UTC, lchojnacki commented on techradar/radars/models.py
> +    slug = models.SlugField(unique=True)
Proponuję zainstalować paczkę `django-extensions` i dodać tu `AutoSlugField`: https://django-extensions.readthedocs.io/en/latest/field_extensions.html

2024-12-20 13:43 UTC, lchojnacki commented on techradar/views.py
> +from django.shortcuts import render
hmm, ten plik wydaje mi się być niepotrzebny :thinking: moim zdaniem do usunięcia :smile:

2024-12-20 13:43 UTC, lchojnacki commented on db.sqlite3
Usuń proszę bazkę danych, nie chcemy jej tu trzymać - po to mamy fixtury :smile:

2024-12-20 13:44 UTC, lchojnacki commented on techradar/__pycache__/__init__.cpython-313.pyc
usunięte :+1:

2024-12-20 13:48 UTC, lchojnacki commented on README.md
> +# tech-radar-admin
Dodaj do readme instrukcję, jak zasetupować aplikację lokalnie. Powinny się w niej znaleźć takie kroki:

1. Stwórz venv z odpowiednią wersją pythona (wpisz taką, jakiej Ty używasz) i aktywuj go
2. Zainstaluj paczki: `pip install -r requirements.txt`
3. Zmigruj bazę: `python manage.py migrate`
4. Wczytaj fixtury: `python manage.py loaddata fixtures/*.yaml`
5. Uruchom serwer: `python manage.py runserver`

Warto też umieścić tu tabelkę z domyślnymi użytkownikami:

```
| Username | Password  |
|----------|-----------|
| admin    | admin321! |
```

2025-01-08 16:37 UTC, lchojnacki requested changes

2025-01-08 16:37 UTC, lchojnacki commented on techradar/radars/models.py
> +    slug = AutoSlugField(populate_from='title')
Czy to na pewno działa? :thinking: `populate_from` powinien wskazywać na jedno z istniejących pól, a ten model posiada tylko pole `label` :smile:

2025-01-08 16:37 UTC, lchojnacki commented on techradar/settings.py
> +]
Przyjemnie pracuje się z projektem, kiedy appki należące do projektu (te zaczynające się od `techradar.`) są wydzielone lub umieszczone na samym końcu. Osobiście jestem fanem takiego rozwiązania:

```suggestion
PROJECT_APPS = [
    'techradar.radars',
]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
] + PROJECT_APPS
```

2025-01-08 16:37 UTC, lchojnacki commented on techradar/radars/migrations/0002_alter_radar_slug.py
> +# Generated by Django 5.1.4 on 2025-01-03 07:47
Jeśli nie ma takiej konieczności (a najczęściej nie ma), to staraj się unikać dodawania więcej niż jednej migracji per appka w jednym PR. Jako, że to dopiero pierwsze migracje w całym projekcie, to możesz po prostu usunąć swój plik bazy sqlite, usunąć te dwa pliki i stworzyć od nowa plik 0001 (`python manage.py makemigrations`).

Hint: jak będziesz zmieniać argument `populate_from` to django też będzie chciało dodać migrację, warto tamtą zmianę zrobić wcześniej :slightly_smiling_face:

2025-01-08 16:43 UTC, lchojnacki commented
Nie dodawałem tej uwagi wcześniej, ale myślę że warto dodać od razu konfigurację pre-commita: https://pypi.org/project/pre-commit/

1. Dodaj w głównym katalogu plik o nazwie `.pre-commit-config.yaml`
2. Uzupełnij plik zawartością:
```yaml
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-toml
  - id: check-yaml
  - id: check-merge-conflict

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.8.6
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format

- repo: https://github.com/adamchainz/django-upgrade
  rev: "1.22.2"
  hooks:
    - id: django-upgrade
      args: [ --target-version, "5.1" ]
```
3. Dodaj paczkę pre-commit do requirements i zainstaluj
4. Zainstaluj hooki: `pre-commit install` (dodaj tę informację też do readme, to będzie konieczny krok przy setupie projektu)
5. Wykonaj hooki na wszystkich plikach: `pre-commit run --all-files`

To powinno sformatować cały Twój kod, w razie problemów służę pomocą :smile: przed każdym kolejnym commitem sprawdzane i formatowane będą tylko nowe zmiany w repo.

2025-01-10 10:16 UTC, justgruba commented on techradar/radars/models.py
> +    slug = AutoSlugField(populate_from='title')
Racja xd nie wiem skąd ja to wzięłam xd

2025-01-10 10:22 UTC, justgruba commented on techradar/radars/migrations/0002_alter_radar_slug.py
> +# Generated by Django 5.1.4 on 2025-01-03 07:47
O dziękuję to nie wiedziałam, że tak się robi

2025-01-10 11:36 UTC, lchojnacki commented on techradar/radars/migrations/0002_alter_radar_slug.py
> +# Generated by Django 5.1.4 on 2025-01-03 07:47
można tego nie robić, ale wtedy liczba migracji bardzo szybko rośnie, co z czasem może utrudnić utrzymanie projektu :smile:

2025-01-10 12:36 UTC, lchojnacki approved these changes

2025-01-10 12:41 UTC, merged